--
- name: Allow rhsm a longer timeout to help out with subscription-manager
  lineinfile:
    dest: /etc/rhsm/rhsm.conf
    line: 'server_timeout=600'
    insertafter: '^proxy_password ='
 
- name: Satellite bootstrap post
  command: "rpm -ivh http://{{rhsm_server_hostname}}/pub/{{sat_bootstrap_rpm}} --force"
 
- name: Register host via Activation key
  command: subscription-manager register --org {{ rhsm_org_id }} --activationkey {{ rhsm_activation_key }} --force
